Feature/cvsb 19017
dvsa/cvs-svc-trailer-registration pull request #3
Opened 2020-12-17 12:27 UTC by JonLazariniDD

2021-01-08 10:47 UTC, JonLazariniDD commented
I was thinking that if we wish to replicate this scaffold project we could leave the history until 1.0.0 which should be our starting point from releasing changes now since the configuration is done as this would help cherry picking (or not) changes if we didn't want to start with the same baseline or modifying this further? Thoughts?

2021-02-02 09:12 UTC, m-ujaffer commented on .npmrc
> +versions = true
linebreak

2021-02-02 09:12 UTC, m-ujaffer commented on .nvmrc
> +12.5.0
linebreak

2021-02-02 09:12 UTC, m-ujaffer commented on .prettierignore
> +.build
linebreak

2021-02-02 09:13 UTC, m-ujaffer commented on .secignore
> +.npmrc
linebreak

2021-02-02 09:14 UTC, m-ujaffer commented on .editorconfig
> +indent_style = tab
line break

2021-02-02 09:15 UTC, m-ujaffer commented on .eslintignore
> +.build
linebreak

2021-03-19 00:47 UTC, m-ujaffer requested changes
A very good repository and can be used to build new services. I would recommend to strip out some keywords specific to trailer registration and setup as a scaffolding which can be cloned to make new micro-services. There are a few minor which need to be looked at.

2021-03-19 00:47 UTC, m-ujaffer commented on package.json
> +    "build": "npm-run-all clean build:dev",
nice

2021-03-19 00:47 UTC, m-ujaffer commented on README.md
> +- <b>build</b>: `npm run build` - _bundle the project for production_
minor tweak needed as production and dev build are two separate scripts.

2021-03-30 16:26 UTC, m-ujaffer commented
closing in favour of https://github.com/dvsa/cvs-svc-template

2021-03-30 16:26 UTC, closed without merging